/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { FacilityWhereUniqueInput } from "../../facility/base/FacilityWhereUniqueInput";
import { Type } from "class-transformer";
import { JobUpdateManyWithoutAssetsInput } from "./JobUpdateManyWithoutAssetsInput";
import { ContactUpdateManyWithoutAssetsInput } from "./ContactUpdateManyWithoutAssetsInput";
@InputType()
class AssetUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  assetName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  assetType?: string | null;

  @ApiProperty({
    required: false,
    type: () => FacilityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FacilityWhereUniqueInput)
  @IsOptional()
  @Field(() => FacilityWhereUniqueInput, {
    nullable: true,
  })
  facility?: FacilityWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => JobUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => JobUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => JobUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  jobs?: JobUpdateManyWithoutAssetsInput;

  @ApiProperty({
    required: false,
    type: () => ContactUpdateManyWithoutAssetsInput,
  })
  @ValidateNested()
  @Type(() => ContactUpdateManyWithoutAssetsInput)
  @IsOptional()
  @Field(() => ContactUpdateManyWithoutAssetsInput, {
    nullable: true,
  })
  poc?: ContactUpdateManyWithoutAssetsInput;
}
export { AssetUpdateInput };
