/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { ContactListRelationFilter } from "../../contact/base/ContactListRelationFilter";
import { FacilityListRelationFilter } from "../../facility/base/FacilityListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { JobListRelationFilter } from "../../job/base/JobListRelationFilter";
@InputType()
class CompanyWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  companyName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ContactListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ContactListRelationFilter)
  @IsOptional()
  @Field(() => ContactListRelationFilter, {
    nullable: true,
  })
  contacts?: ContactListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => FacilityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => FacilityListRelationFilter)
  @IsOptional()
  @Field(() => FacilityListRelationFilter, {
    nullable: true,
  })
  facilities?: FacilityListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => JobListRelationFilter,
  })
  @ValidateNested()
  @Type(() => JobListRelationFilter)
  @IsOptional()
  @Field(() => JobListRelationFilter, {
    nullable: true,
  })
  jobs?: JobListRelationFilter;
}
export { CompanyWhereInput };
