/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ContactCreateNestedManyWithoutCompaniesInput } from "./ContactCreateNestedManyWithoutCompaniesInput";
import { Type } from "class-transformer";
import { FacilityCreateNestedManyWithoutCompaniesInput } from "./FacilityCreateNestedManyWithoutCompaniesInput";
import { JobCreateNestedManyWithoutCompaniesInput } from "./JobCreateNestedManyWithoutCompaniesInput";
@InputType()
class CompanyCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  companyName?: string | null;

  @ApiProperty({
    required: false,
    type: () => ContactCreateNestedManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => ContactCreateNestedManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => ContactCreateNestedManyWithoutCompaniesInput, {
    nullable: true,
  })
  contacts?: ContactCreateNestedManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => FacilityCreateNestedManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => FacilityCreateNestedManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => FacilityCreateNestedManyWithoutCompaniesInput, {
    nullable: true,
  })
  facilities?: FacilityCreateNestedManyWithoutCompaniesInput;

  @ApiProperty({
    required: false,
    type: () => JobCreateNestedManyWithoutCompaniesInput,
  })
  @ValidateNested()
  @Type(() => JobCreateNestedManyWithoutCompaniesInput)
  @IsOptional()
  @Field(() => JobCreateNestedManyWithoutCompaniesInput, {
    nullable: true,
  })
  jobs?: JobCreateNestedManyWithoutCompaniesInput;
}
export { CompanyCreateInput };
