/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssetUpdateManyWithoutContactsInput } from "./AssetUpdateManyWithoutContactsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import { FacilityUpdateManyWithoutContactsInput } from "./FacilityUpdateManyWithoutContactsInput";
@InputType()
class ContactUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AssetUpdateManyWithoutContactsInput,
  })
  @ValidateNested()
  @Type(() => AssetUpdateManyWithoutContactsInput)
  @IsOptional()
  @Field(() => AssetUpdateManyWithoutContactsInput, {
    nullable: true,
  })
  assets?: AssetUpdateManyWithoutContactsInput;

  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  company?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => FacilityUpdateManyWithoutContactsInput,
  })
  @ValidateNested()
  @Type(() => FacilityUpdateManyWithoutContactsInput)
  @IsOptional()
  @Field(() => FacilityUpdateManyWithoutContactsInput, {
    nullable: true,
  })
  facilities?: FacilityUpdateManyWithoutContactsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;
}
export { ContactUpdateInput };
