/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AssetCreateNestedManyWithoutContactsInput } from "./AssetCreateNestedManyWithoutContactsInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CompanyWhereUniqueInput } from "../../company/base/CompanyWhereUniqueInput";
import { FacilityCreateNestedManyWithoutContactsInput } from "./FacilityCreateNestedManyWithoutContactsInput";
@InputType()
class ContactCreateInput {
  @ApiProperty({
    required: false,
    type: () => AssetCreateNestedManyWithoutContactsInput,
  })
  @ValidateNested()
  @Type(() => AssetCreateNestedManyWithoutContactsInput)
  @IsOptional()
  @Field(() => AssetCreateNestedManyWithoutContactsInput, {
    nullable: true,
  })
  assets?: AssetCreateNestedManyWithoutContactsInput;

  @ApiProperty({
    required: false,
    type: () => CompanyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CompanyWhereUniqueInput)
  @IsOptional()
  @Field(() => CompanyWhereUniqueInput, {
    nullable: true,
  })
  company?: CompanyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => FacilityCreateNestedManyWithoutContactsInput,
  })
  @ValidateNested()
  @Type(() => FacilityCreateNestedManyWithoutContactsInput)
  @IsOptional()
  @Field(() => FacilityCreateNestedManyWithoutContactsInput, {
    nullable: true,
  })
  facilities?: FacilityCreateNestedManyWithoutContactsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;
}
export { ContactCreateInput };
