/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateTechnicianArgs } from "./CreateTechnicianArgs";
import { UpdateTechnicianArgs } from "./UpdateTechnicianArgs";
import { DeleteTechnicianArgs } from "./DeleteTechnicianArgs";
import { TechnicianFindManyArgs } from "./TechnicianFindManyArgs";
import { TechnicianFindUniqueArgs } from "./TechnicianFindUniqueArgs";
import { Technician } from "./Technician";
import { User } from "../../user/base/User";
import { TechnicianService } from "../technician.service";

@graphql.Resolver(() => Technician)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TechnicianResolverBase {
  constructor(
    protected readonly service: TechnicianService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Technician",
    action: "read",
    possession: "any",
  })
  async _techniciansMeta(
    @graphql.Args() args: TechnicianFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Technician])
  @nestAccessControl.UseRoles({
    resource: "Technician",
    action: "read",
    possession: "any",
  })
  async technicians(
    @graphql.Args() args: TechnicianFindManyArgs
  ): Promise<Technician[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Technician, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Technician",
    action: "read",
    possession: "own",
  })
  async technician(
    @graphql.Args() args: TechnicianFindUniqueArgs
  ): Promise<Technician | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Technician)
  @nestAccessControl.UseRoles({
    resource: "Technician",
    action: "create",
    possession: "any",
  })
  async createTechnician(
    @graphql.Args() args: CreateTechnicianArgs
  ): Promise<Technician> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        userId: args.data.userId
          ? {
              connect: args.data.userId,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Technician)
  @nestAccessControl.UseRoles({
    resource: "Technician",
    action: "update",
    possession: "any",
  })
  async updateTechnician(
    @graphql.Args() args: UpdateTechnicianArgs
  ): Promise<Technician | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          userId: args.data.userId
            ? {
                connect: args.data.userId,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Technician)
  @nestAccessControl.UseRoles({
    resource: "Technician",
    action: "delete",
    possession: "any",
  })
  async deleteTechnician(
    @graphql.Args() args: DeleteTechnicianArgs
  ): Promise<Technician | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async userId(@graphql.Parent() parent: Technician): Promise<User | null> {
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
